version: '3.9'

services:

  postgres:
    container_name: postgres
    image: lcube_postgres
    build: ./POSTGRES
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: dpgadmin
    image: bitnami/phppgadmin:latest
    environment:
      DATABASE_HOST: postgres

    ports: 
      - "8080:8080"
      - "443:8143"
    depends_on:
      - postgres

  app:
    container_name: dennys_app
    image: dennys_app
    build:
      context: app #name of the folder
    depends_on:
      - postgres

volumes:
  pgdata: {}